/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the OperatingSystemIpxeArtifact type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatingSystemIpxeArtifact{}

// OperatingSystemIpxeArtifact An artifact (kernel, initrd, ISO, ...) referenced by an iPXE OS definition
type OperatingSystemIpxeArtifact struct {
	// Artifact name
	Name *string `json:"name,omitempty"`
	// Original URL for the artifact
	Url *string `json:"url,omitempty"`
	// Optional SHA256 checksum
	Sha NullableString `json:"sha,omitempty"`
	// Optional auth type: Basic or Bearer
	AuthType NullableString `json:"authType,omitempty"`
	// Optional auth token. Redacted in API responses.
	AuthToken NullableString `json:"authToken,omitempty"`
	// How to handle caching for this artifact
	CacheStrategy *string `json:"cacheStrategy,omitempty"`
}

// NewOperatingSystemIpxeArtifact instantiates a new OperatingSystemIpxeArtifact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatingSystemIpxeArtifact() *OperatingSystemIpxeArtifact {
	this := OperatingSystemIpxeArtifact{}
	return &this
}

// NewOperatingSystemIpxeArtifactWithDefaults instantiates a new OperatingSystemIpxeArtifact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatingSystemIpxeArtifactWithDefaults() *OperatingSystemIpxeArtifact {
	this := OperatingSystemIpxeArtifact{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OperatingSystemIpxeArtifact) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatingSystemIpxeArtifact) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OperatingSystemIpxeArtifact) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OperatingSystemIpxeArtifact) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *OperatingSystemIpxeArtifact) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatingSystemIpxeArtifact) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *OperatingSystemIpxeArtifact) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *OperatingSystemIpxeArtifact) SetUrl(v string) {
	o.Url = &v
}

// GetSha returns the Sha field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OperatingSystemIpxeArtifact) GetSha() string {
	if o == nil || IsNil(o.Sha.Get()) {
		var ret string
		return ret
	}
	return *o.Sha.Get()
}

// GetShaOk returns a tuple with the Sha field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperatingSystemIpxeArtifact) GetShaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sha.Get(), o.Sha.IsSet()
}

// HasSha returns a boolean if a field has been set.
func (o *OperatingSystemIpxeArtifact) HasSha() bool {
	if o != nil && o.Sha.IsSet() {
		return true
	}

	return false
}

// SetSha gets a reference to the given NullableString and assigns it to the Sha field.
func (o *OperatingSystemIpxeArtifact) SetSha(v string) {
	o.Sha.Set(&v)
}

// SetShaNil sets the value for Sha to be an explicit nil
func (o *OperatingSystemIpxeArtifact) SetShaNil() {
	o.Sha.Set(nil)
}

// UnsetSha ensures that no value is present for Sha, not even an explicit nil
func (o *OperatingSystemIpxeArtifact) UnsetSha() {
	o.Sha.Unset()
}

// GetAuthType returns the AuthType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OperatingSystemIpxeArtifact) GetAuthType() string {
	if o == nil || IsNil(o.AuthType.Get()) {
		var ret string
		return ret
	}
	return *o.AuthType.Get()
}

// GetAuthTypeOk returns a tuple with the AuthType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperatingSystemIpxeArtifact) GetAuthTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthType.Get(), o.AuthType.IsSet()
}

// HasAuthType returns a boolean if a field has been set.
func (o *OperatingSystemIpxeArtifact) HasAuthType() bool {
	if o != nil && o.AuthType.IsSet() {
		return true
	}

	return false
}

// SetAuthType gets a reference to the given NullableString and assigns it to the AuthType field.
func (o *OperatingSystemIpxeArtifact) SetAuthType(v string) {
	o.AuthType.Set(&v)
}

// SetAuthTypeNil sets the value for AuthType to be an explicit nil
func (o *OperatingSystemIpxeArtifact) SetAuthTypeNil() {
	o.AuthType.Set(nil)
}

// UnsetAuthType ensures that no value is present for AuthType, not even an explicit nil
func (o *OperatingSystemIpxeArtifact) UnsetAuthType() {
	o.AuthType.Unset()
}

// GetAuthToken returns the AuthToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OperatingSystemIpxeArtifact) GetAuthToken() string {
	if o == nil || IsNil(o.AuthToken.Get()) {
		var ret string
		return ret
	}
	return *o.AuthToken.Get()
}

// GetAuthTokenOk returns a tuple with the AuthToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OperatingSystemIpxeArtifact) GetAuthTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthToken.Get(), o.AuthToken.IsSet()
}

// HasAuthToken returns a boolean if a field has been set.
func (o *OperatingSystemIpxeArtifact) HasAuthToken() bool {
	if o != nil && o.AuthToken.IsSet() {
		return true
	}

	return false
}

// SetAuthToken gets a reference to the given NullableString and assigns it to the AuthToken field.
func (o *OperatingSystemIpxeArtifact) SetAuthToken(v string) {
	o.AuthToken.Set(&v)
}

// SetAuthTokenNil sets the value for AuthToken to be an explicit nil
func (o *OperatingSystemIpxeArtifact) SetAuthTokenNil() {
	o.AuthToken.Set(nil)
}

// UnsetAuthToken ensures that no value is present for AuthToken, not even an explicit nil
func (o *OperatingSystemIpxeArtifact) UnsetAuthToken() {
	o.AuthToken.Unset()
}

// GetCacheStrategy returns the CacheStrategy field value if set, zero value otherwise.
func (o *OperatingSystemIpxeArtifact) GetCacheStrategy() string {
	if o == nil || IsNil(o.CacheStrategy) {
		var ret string
		return ret
	}
	return *o.CacheStrategy
}

// GetCacheStrategyOk returns a tuple with the CacheStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatingSystemIpxeArtifact) GetCacheStrategyOk() (*string, bool) {
	if o == nil || IsNil(o.CacheStrategy) {
		return nil, false
	}
	return o.CacheStrategy, true
}

// HasCacheStrategy returns a boolean if a field has been set.
func (o *OperatingSystemIpxeArtifact) HasCacheStrategy() bool {
	if o != nil && !IsNil(o.CacheStrategy) {
		return true
	}

	return false
}

// SetCacheStrategy gets a reference to the given string and assigns it to the CacheStrategy field.
func (o *OperatingSystemIpxeArtifact) SetCacheStrategy(v string) {
	o.CacheStrategy = &v
}

func (o OperatingSystemIpxeArtifact) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatingSystemIpxeArtifact) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if o.Sha.IsSet() {
		toSerialize["sha"] = o.Sha.Get()
	}
	if o.AuthType.IsSet() {
		toSerialize["authType"] = o.AuthType.Get()
	}
	if o.AuthToken.IsSet() {
		toSerialize["authToken"] = o.AuthToken.Get()
	}
	if !IsNil(o.CacheStrategy) {
		toSerialize["cacheStrategy"] = o.CacheStrategy
	}
	return toSerialize, nil
}

type NullableOperatingSystemIpxeArtifact struct {
	value *OperatingSystemIpxeArtifact
	isSet bool
}

func (v NullableOperatingSystemIpxeArtifact) Get() *OperatingSystemIpxeArtifact {
	return v.value
}

func (v *NullableOperatingSystemIpxeArtifact) Set(val *OperatingSystemIpxeArtifact) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatingSystemIpxeArtifact) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatingSystemIpxeArtifact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatingSystemIpxeArtifact(val *OperatingSystemIpxeArtifact) *NullableOperatingSystemIpxeArtifact {
	return &NullableOperatingSystemIpxeArtifact{value: val, isSet: true}
}

func (v NullableOperatingSystemIpxeArtifact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatingSystemIpxeArtifact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
