/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the OperatingSystemIpxeParameter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatingSystemIpxeParameter{}

// OperatingSystemIpxeParameter A name/value parameter passed to an iPXE template
type OperatingSystemIpxeParameter struct {
	// Parameter name (used as a variable in the template)
	Name *string `json:"name,omitempty"`
	// Parameter value
	Value *string `json:"value,omitempty"`
}

// NewOperatingSystemIpxeParameter instantiates a new OperatingSystemIpxeParameter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatingSystemIpxeParameter() *OperatingSystemIpxeParameter {
	this := OperatingSystemIpxeParameter{}
	return &this
}

// NewOperatingSystemIpxeParameterWithDefaults instantiates a new OperatingSystemIpxeParameter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatingSystemIpxeParameterWithDefaults() *OperatingSystemIpxeParameter {
	this := OperatingSystemIpxeParameter{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OperatingSystemIpxeParameter) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatingSystemIpxeParameter) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OperatingSystemIpxeParameter) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OperatingSystemIpxeParameter) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *OperatingSystemIpxeParameter) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatingSystemIpxeParameter) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *OperatingSystemIpxeParameter) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *OperatingSystemIpxeParameter) SetValue(v string) {
	o.Value = &v
}

func (o OperatingSystemIpxeParameter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatingSystemIpxeParameter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableOperatingSystemIpxeParameter struct {
	value *OperatingSystemIpxeParameter
	isSet bool
}

func (v NullableOperatingSystemIpxeParameter) Get() *OperatingSystemIpxeParameter {
	return v.value
}

func (v *NullableOperatingSystemIpxeParameter) Set(val *OperatingSystemIpxeParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatingSystemIpxeParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatingSystemIpxeParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatingSystemIpxeParameter(val *OperatingSystemIpxeParameter) *NullableOperatingSystemIpxeParameter {
	return &NullableOperatingSystemIpxeParameter{value: val, isSet: true}
}

func (v NullableOperatingSystemIpxeParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatingSystemIpxeParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
