// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the IpxeTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpxeTemplate{}

// IpxeTemplate An iPXE script template propagated (read-only) from nico-core
type IpxeTemplate struct {
	// Stable template UUID assigned by core
	Id *string `json:"id,omitempty"`
	// Globally unique template name
	Name *string `json:"name,omitempty"`
	// Raw iPXE script content
	Template *string `json:"template,omitempty"`
	// Parameters that must be provided to render the template
	RequiredParams []string `json:"requiredParams,omitempty"`
	// Parameters reserved by the template and not user-supplied
	ReservedParams []string `json:"reservedParams,omitempty"`
	// Artifact names required for the template
	RequiredArtifacts []string `json:"requiredArtifacts,omitempty"`
	// Template visibility: Internal or Public
	Visibility *string    `json:"visibility,omitempty"`
	Created    *time.Time `json:"created,omitempty"`
	Updated    *time.Time `json:"updated,omitempty"`
}

// NewIpxeTemplate instantiates a new IpxeTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpxeTemplate() *IpxeTemplate {
	this := IpxeTemplate{}
	return &this
}

// NewIpxeTemplateWithDefaults instantiates a new IpxeTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpxeTemplateWithDefaults() *IpxeTemplate {
	this := IpxeTemplate{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IpxeTemplate) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpxeTemplate) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IpxeTemplate) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *IpxeTemplate) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IpxeTemplate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpxeTemplate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IpxeTemplate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IpxeTemplate) SetName(v string) {
	o.Name = &v
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *IpxeTemplate) GetTemplate() string {
	if o == nil || IsNil(o.Template) {
		var ret string
		return ret
	}
	return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpxeTemplate) GetTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.Template) {
		return nil, false
	}
	return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *IpxeTemplate) HasTemplate() bool {
	if o != nil && !IsNil(o.Template) {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given string and assigns it to the Template field.
func (o *IpxeTemplate) SetTemplate(v string) {
	o.Template = &v
}

// GetRequiredParams returns the RequiredParams field value if set, zero value otherwise.
func (o *IpxeTemplate) GetRequiredParams() []string {
	if o == nil || IsNil(o.RequiredParams) {
		var ret []string
		return ret
	}
	return o.RequiredParams
}

// GetRequiredParamsOk returns a tuple with the RequiredParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpxeTemplate) GetRequiredParamsOk() ([]string, bool) {
	if o == nil || IsNil(o.RequiredParams) {
		return nil, false
	}
	return o.RequiredParams, true
}

// HasRequiredParams returns a boolean if a field has been set.
func (o *IpxeTemplate) HasRequiredParams() bool {
	if o != nil && !IsNil(o.RequiredParams) {
		return true
	}

	return false
}

// SetRequiredParams gets a reference to the given []string and assigns it to the RequiredParams field.
func (o *IpxeTemplate) SetRequiredParams(v []string) {
	o.RequiredParams = v
}

// GetReservedParams returns the ReservedParams field value if set, zero value otherwise.
func (o *IpxeTemplate) GetReservedParams() []string {
	if o == nil || IsNil(o.ReservedParams) {
		var ret []string
		return ret
	}
	return o.ReservedParams
}

// GetReservedParamsOk returns a tuple with the ReservedParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpxeTemplate) GetReservedParamsOk() ([]string, bool) {
	if o == nil || IsNil(o.ReservedParams) {
		return nil, false
	}
	return o.ReservedParams, true
}

// HasReservedParams returns a boolean if a field has been set.
func (o *IpxeTemplate) HasReservedParams() bool {
	if o != nil && !IsNil(o.ReservedParams) {
		return true
	}

	return false
}

// SetReservedParams gets a reference to the given []string and assigns it to the ReservedParams field.
func (o *IpxeTemplate) SetReservedParams(v []string) {
	o.ReservedParams = v
}

// GetRequiredArtifacts returns the RequiredArtifacts field value if set, zero value otherwise.
func (o *IpxeTemplate) GetRequiredArtifacts() []string {
	if o == nil || IsNil(o.RequiredArtifacts) {
		var ret []string
		return ret
	}
	return o.RequiredArtifacts
}

// GetRequiredArtifactsOk returns a tuple with the RequiredArtifacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpxeTemplate) GetRequiredArtifactsOk() ([]string, bool) {
	if o == nil || IsNil(o.RequiredArtifacts) {
		return nil, false
	}
	return o.RequiredArtifacts, true
}

// HasRequiredArtifacts returns a boolean if a field has been set.
func (o *IpxeTemplate) HasRequiredArtifacts() bool {
	if o != nil && !IsNil(o.RequiredArtifacts) {
		return true
	}

	return false
}

// SetRequiredArtifacts gets a reference to the given []string and assigns it to the RequiredArtifacts field.
func (o *IpxeTemplate) SetRequiredArtifacts(v []string) {
	o.RequiredArtifacts = v
}

// GetVisibility returns the Visibility field value if set, zero value otherwise.
func (o *IpxeTemplate) GetVisibility() string {
	if o == nil || IsNil(o.Visibility) {
		var ret string
		return ret
	}
	return *o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpxeTemplate) GetVisibilityOk() (*string, bool) {
	if o == nil || IsNil(o.Visibility) {
		return nil, false
	}
	return o.Visibility, true
}

// HasVisibility returns a boolean if a field has been set.
func (o *IpxeTemplate) HasVisibility() bool {
	if o != nil && !IsNil(o.Visibility) {
		return true
	}

	return false
}

// SetVisibility gets a reference to the given string and assigns it to the Visibility field.
func (o *IpxeTemplate) SetVisibility(v string) {
	o.Visibility = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *IpxeTemplate) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpxeTemplate) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *IpxeTemplate) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *IpxeTemplate) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *IpxeTemplate) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpxeTemplate) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *IpxeTemplate) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *IpxeTemplate) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o IpxeTemplate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpxeTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Template) {
		toSerialize["template"] = o.Template
	}
	if !IsNil(o.RequiredParams) {
		toSerialize["requiredParams"] = o.RequiredParams
	}
	if !IsNil(o.ReservedParams) {
		toSerialize["reservedParams"] = o.ReservedParams
	}
	if !IsNil(o.RequiredArtifacts) {
		toSerialize["requiredArtifacts"] = o.RequiredArtifacts
	}
	if !IsNil(o.Visibility) {
		toSerialize["visibility"] = o.Visibility
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableIpxeTemplate struct {
	value *IpxeTemplate
	isSet bool
}

func (v NullableIpxeTemplate) Get() *IpxeTemplate {
	return v.value
}

func (v *NullableIpxeTemplate) Set(val *IpxeTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableIpxeTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableIpxeTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpxeTemplate(val *IpxeTemplate) *NullableIpxeTemplate {
	return &NullableIpxeTemplate{value: val, isSet: true}
}

func (v NullableIpxeTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpxeTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
